"""activities update

Revision ID: 7e5af4e689e0
Revises: c0fa1c51c0e7
Create Date: 2025-10-28 12:32:41.704409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e5af4e689e0'
down_revision: Union[str, Sequence[str], None] = 'c0fa1c51c0e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('parent_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'parent_id')
    # ### end Alembic commands ###
