"""make building_id nullable in organizations

Revision ID: 8bc45e63b444
Revises: 871715e7dd42
Create Date: 2025-10-26 10:45:24.375845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bc45e63b444'
down_revision: Union[str, Sequence[str], None] = '871715e7dd42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'building_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'building_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
