"""make organization_id nullable in phones

Revision ID: b48c23d6e964
Revises: 8bc45e63b444
Create Date: 2025-10-26 15:33:49.533386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b48c23d6e964'
down_revision: Union[str, Sequence[str], None] = '8bc45e63b444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('phones', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('phones', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
