"""add default path generation

Revision ID: f62dd3eef865
Revises: 7e5af4e689e0
Create Date: 2025-10-28 13:09:04.426006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f62dd3eef865'
down_revision: Union[str, Sequence[str], None] = '7e5af4e689e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'parent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('parent_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
