services:
  app:
    build: .
    container_name: mkk_luna_app
    ports:
      - "8001:80"
    volumes:
      - ./app:/code/app
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: postgres:15
    container_name: mkk_luna_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h ${POSTGRES_HOST}"]
      timeout: 5s
      retries: 5
      start_period: 3s

volumes:
  db_data: