services:
  app:
    build: .
    container_name: mkk_luna_app
    ports:
      - "8001:80"
    restart: always
    env_file:
      - .env
    depends_on:
      - db
  
  db:
    image: postgres:15
    container_name: mkk_luna_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: